### ISSUE TITLE
Type a message text, slide to cancel text and Emoji Image

### ISSUE THREAD

**Issue by MaxAndolini** [varunjohn/Audio-Recording-Animation#11]
We must be able to change them ourselves.

Type a message text, slide to cancel text and Emoji Image.

@varunjohn

**Comment by varunjohn** [comment]
I have mentioned in README.. 

        audioRecordView.getMessageView().setHint(stringResourceId);
        audioRecordView.changeSlideToCancelText(stringResourceId);
        ((ImageView) audioRecordView.getEmojiView()).setImageResource(drawableResourceId);

**Comment by MaxAndolini** [comment]
Fixed, thanks.
