### ISSUE TITLE
Duplicated from previous line.

### ISSUE THREAD

**Issue by DHosseiny** [varunjohn/Audio-Recording-Animation#2]
did you mean "motionY > directionOffset"?

https://github.com/varunjohn/Audio-Recording-Animation/blob/b246459eed01efdaae5724851a047013c4e41dd4/app/src/main/java/com/varunjohn1990/audiorecordingview/AudioRecordView.java#L251

**Comment by varunjohn** [comment]
Nope.. all good.. 
you can delete that line..
