### ISSUE TITLE
Implememtation

### ISSUE THREAD

**Issue by ChatPost08** [varunjohn/Audio-Recording-Animation#6]
How can I implement this in my android studio application?

**Comment by karmac2015** [comment]
Did you know how to implement it in android studio app ?

**Comment by ChatPost08** [comment]
> Did you know how to implement it in android studio app ?

Not yet @karmac2015

**Comment by varunjohn** [comment]
i have updated to version 2. now you can add the library as gradle dependency. check the new documentation.
